#!/usr/bin/env sh

VSROOT="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
ROOT="$(dirname "$(dirname "$VSROOT")")"

APP_NAME="code-deno"
VERSION="1.108.2"
COMMIT="3c0b449c6e6e37b44a8a7938c0d8a3049926a64c"
EXEC_NAME="code-deno"
CLI_SCRIPT="$VSROOT/out/server-cli.js"

deno run --sloppy-imports --config /workspace/deno.jsonc  "$CLI_SCRIPT" "$APP_NAME" "$VERSION" "$COMMIT" "$EXEC_NAME" "$@"
